REVOKE ALL ON FUNCTION public.gen_room_code() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_room(text, integer, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.join_room(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.list_public_rooms() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_room_ready(uuid, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.leave_room(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.host_update_room(uuid, text, integer, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.start_room_match(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reset_room(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.my_active_room() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_room_member(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_room_host(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_room(text, integer, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.join_room(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_public_rooms() TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_room_ready(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leave_room(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.host_update_room(uuid, text, integer, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.start_room_match(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reset_room(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_active_room() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_room_member(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_room_host(uuid, uuid) TO authenticated;